version: '3.7'
services:
  database:
    image: postgres:16
    restart: always
    environment:                 
      POSTGRES_USER: 'admin'     
      POSTGRES_PASSWORD: 'admin' 
      POSTGRES_DB: 'smartway_db'  
    networks:
      - backend
    ports:
      - "5431:5432"             
    volumes:
      - database-pg:/var/lib/postgresql/data
  api:
    build:
      context: ./
      dockerfile: ./Api/Dockerfile
    networks:
      - backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

networks:
  backend:
    driver: bridge

volumes:
  database-pg:
    
