//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartway_task.Scripts.Employees {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostgresEmployeeElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostgresEmployeeElement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smartway_task.Scripts.Employees.PostgresEmployeeElement", typeof(PostgresEmployeeElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO employees (name, surname, phone, companyid, departmentid) VALUES (@name, @surname, @phone, @companyid, @departmentid) RETURNING Id as &quot;&quot;Id&quot;&quot;.
        /// </summary>
        internal static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 1 FROM employees WHERE companyid = @companyId LIMIT 1.
        /// </summary>
        internal static string CheckExistingCompanyId {
            get {
                return ResourceManager.GetString("CheckExistingCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Employees WHERE id = @id.
        /// </summary>
        internal static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT e.id, e.name as &quot;&quot;Name&quot;&quot;, e.surname as &quot;&quot;Surname&quot;&quot;, e.phone as &quot;&quot;Phone&quot;&quot;, e.companyid as &quot;&quot;CompanyId&quot;&quot;, e.departmentid as &quot;&quot;DepartmentId&quot;&quot;,
        ///        p.id, p.type as &quot;&quot;Type&quot;&quot;, p.number as &quot;&quot;Number&quot;&quot;, p.employeeid as &quot;&quot;EmployeeId&quot;&quot;,
        ///        d.id, d.name as &quot;&quot;Name&quot;&quot;, d.phone as &quot;&quot;Phone&quot;&quot;
        ///FROM employees e
        ///         LEFT JOIN passports p ON p.EmployeeId = e.Id
        ///         LEFT JOIN departments d ON d.Id = e.DepartmentId
        ///WHERE e.companyid = @companyId.
        /// </summary>
        internal static string GetEmployeeByCompanyId {
            get {
                return ResourceManager.GetString("GetEmployeeByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT e.id, e.name as &quot;&quot;Name&quot;&quot;, e.surname as &quot;&quot;Surname&quot;&quot;, e.phone as &quot;&quot;Phone&quot;&quot;, e.companyid as &quot;&quot;CompanyId&quot;&quot;, e.departmentid as &quot;&quot;DepartmentId&quot;&quot;,
        ///        p.id, p.type as &quot;&quot;Type&quot;&quot;, p.number as &quot;&quot;Number&quot;&quot;, p.employeeid as &quot;&quot;EmployeeId&quot;&quot;,
        ///        d.id, d.name as &quot;&quot;Name&quot;&quot;, d.phone as &quot;&quot;Phone&quot;&quot;
        ///FROM employees e
        ///         LEFT JOIN passports p ON p.EmployeeId = e.Id
        ///         LEFT JOIN departments d ON d.Id = e.DepartmentId
        ///WHERE e.departmentid = @departmentId.
        /// </summary>
        internal static string GetEmployeeByDepartmentId {
            get {
                return ResourceManager.GetString("GetEmployeeByDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id, name as &quot;&quot;Name&quot;&quot;, surname as &quot;&quot;Surname&quot;&quot;, phone as &quot;&quot;Phone&quot;&quot;, companyid as &quot;&quot;CompanyId&quot;&quot;, departmentid as &quot;&quot;DepartmentId&quot;&quot;
        ///FROM employees
        ///WHERE id = @id.
        /// </summary>
        internal static string GetEmployeeById {
            get {
                return ResourceManager.GetString("GetEmployeeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 1 FROM employees WHERE phone = @phone LIMIT 1.
        /// </summary>
        internal static string GetEmployeeByPhone {
            get {
                return ResourceManager.GetString("GetEmployeeByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id FROM employees WHERE phone = @phone LIMIT 1.
        /// </summary>
        internal static string GetEmployeeIdByPhone {
            get {
                return ResourceManager.GetString("GetEmployeeIdByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE employees SET name = @name, surname = @surname, phone = @phone, companyid = @companyid, departmentid = @departmentid
        ///WHERE id = @Id
        ///    RETURNING id as &quot;&quot;Id&quot;&quot;, name as &quot;&quot;Name&quot;&quot;, surname as &quot;&quot;Surname&quot;&quot;, phone as &quot;&quot;Phone&quot;&quot;, companyid as &quot;&quot;CompanyId&quot;&quot;, departmentid as &quot;&quot;DepartmentId&quot;&quot;.
        /// </summary>
        internal static string UpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployee", resourceCulture);
            }
        }
    }
}
